### ISSUE TITLE
Support for DeathAdder V2 Lite (1532:00A1) (it is a DA V2 Mini, that doesn't include accessories)

### ISSUE THREAD

**Issue by Ariel-MX** [openrazer/razer-drivers#2050] opened 2023-04-17 04:13 UTC
### Device Info

* Name: Razer DeathAdder V2 Lite
* Product Number: RZ01-03340100
* Model Number: RZ01-0334 Gaming Mouse

### Device Information
```
Bus 001 Device 011: ID 1532:00a1 Razer USA, Ltd Razer DeathAdder V2 Lite
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x00a1 
  bcdDevice            2.00
  iManufacturer           1 Razer
  iProduct                2 Razer DeathAdder V2 Lite
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
Device Status:     0x0000
  (Bus Powered)

```

```
drwxr-xr-x 2 root root 220 abr 16 21:46 .
drwxr-xr-x 4 root root 660 abr 16 21:46 ..
lrwxrwxrwx 1 root root  10 abr 16 21:04 usb-FANTECH_MAXFIT61_Mechanical_Keyboard-event-if01 -> ../event11
lrwxrwxrwx 1 root root   9 abr 16 21:04 usb-FANTECH_MAXFIT61_Mechanical_Keyboard-event-kbd -> ../event8
lrwxrwxrwx 1 root root  10 abr 16 21:04 usb-FANTECH_MAXFIT61_Mechanical_Keyboard-if01-event-mouse -> ../event12
lrwxrwxrwx 1 root root   9 abr 16 21:04 usb-FANTECH_MAXFIT61_Mechanical_Keyboard-if01-mouse -> ../mouse1
lrwxrwxrwx 1 root root  10 abr 16 21:46 usb-Razer_Razer_DeathAdder_V2_Lite-event-if01 -> ../event15
lrwxrwxrwx 1 root root  10 abr 16 21:46 usb-Razer_Razer_DeathAdder_V2_Lite-event-mouse -> ../event13
lrwxrwxrwx 1 root root  10 abr 16 21:46 usb-Razer_Razer_DeathAdder_V2_Lite-if01-event-kbd -> ../event14
lrwxrwxrwx 1 root root  10 abr 16 21:46 usb-Razer_Razer_DeathAdder_V2_Lite-if02-event-kbd -> ../event16
lrwxrwxrwx 1 root root   9 abr 16 21:46 usb-Razer_Razer_DeathAdder_V2_Lite-mouse -> ../mouse2

```

<details>

```
001:011:002:DESCRIPTOR         1681704462.829362
 05 01 09 06 A1 01 05 07 19 E0 29 E7 15 00 25 01
 75 01 95 08 81 02 81 01 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 06 81 00 05 08 19 01 29 03 15 00
 25 01 75 01 95 03 91 02 95 05 91 01 C0

001:011:001:DESCRIPTOR         1681704462.829772
 05 01 09 06 A1 01 85 01 05 07 19 E0 29 E7 15 00
 25 01 75 01 95 08 81 02 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 0E 81 00 C0 05 0C 09 01 A1 01 85
 02 19 00 2A 3C 02 15 00 26 3C 02 95 01 75 10 81
 00 75 08 95 0D 81 01 C0 05 01 09 80 A1 01 85 03
 19 81 29 83 15 00 25 01 75 01 95 03 81 02 95 05
 81 01 75 08 95 0E 81 01 C0 05 01 09 00 A1 01 85
 04 09 03 15 00 26 FF 00 35 00 46 FF 00 75 08 95
 0F 81 00 C0 05 01 09 00 A1 01 85 05 09 03 15 00
 26 FF 00 35 00 46 FF 00 75 08 95 0F 81 00 C0

001:011:000:DESCRIPTOR         1681704462.830250
 05 01 09 02 A1 01 09 01 A1 00 05 09 19 01 29 05
 15 00 25 01 75 01 95 05 81 02 75 01 95 03 81 03
 06 00 FF 09 40 75 08 95 02 15 81 25 7F 81 02 05
 01 09 38 15 81 25 7F 75 08 95 01 81 06 09 30 09
 31 16 00 80 26 FF 7F 75 10 95 02 81 06 C0 06 00
 FF 09 02 15 00 25 01 75 08 95 5A B1 01 C0
```

</details>

### Packet Captures

It is a DeathAdder V2 Mini, but comes without the extras that the Mini includes in the box.

### Synapse Screenshots
Exactly same options that the DeathAdder V2 Mini (Same mouse without extra accessories, as mouse grips).

**Comment by z3ntu** [comment] 2023-04-22 20:29
Duplicate of #1912

**Closed as not planned by z3ntu** 2023-04-22 20:29 UTC
Labels: duplicate, Device Support
