### ISSUE TITLE
Add support for Razer-Blade Model 15 Late 2021

### ISSUE THREAD

**Issue by Pretuer** [openrazer/razer-drivers#1775] opened 2022-03-14 17:00 UTC
Hi, I'm wondering what the process is to add support for the Razer Blade 15 (Late 2021)

**Comment by LinuxDonald** [comment] 2022-03-14 17:02
This pr is an example:

https://github.com/openrazer/openrazer/pull/1766/files

**Comment by Pretuer** [comment] 2022-03-14 17:04
1532:0268 is it's device number

**Comment by z3ntu** [comment] 2022-03-26 15:14
Duplicate of #1524

**Closed as completed by z3ntu** 2022-03-26 15:14 UTC
Labels: duplicate
