### ISSUE TITLE
[Blackwidow v3 Mini Hyperspeed] Fn+G Toggles Mic Mute?

### ISSUE THREAD

**Issue by UM-Li** [openrazer/razer-drivers#1811] opened 2022-05-10 05:05 UTC
### Distribution

Arch Linux + KDE Plasma

### Support

- [x] Have you tried rebooting?
- [x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

**Fn+G** on Blackwidow v3 Mini Hyperspeed is supposed to dim backlight, but in my case it also toggles microphone mute.  `xev` prints this when I press **Fn+G**; it seems this key combo really has been interpreted as toggling mic mute:

```
KeymapNotify event, serial 40, synthetic NO, window 0x0,
    keys:  2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   64  0   0   0   0   0   0   0   

KeyRelease event, serial 40, synthetic NO, window 0xe200001,
    root 0x712, subw 0x0, time 71318942, (591,455), root:(1462,922),
    state 0x0, keycode 198 (keysym 0x1008ffb2, XF86AudioMicMute), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

I don't know how to stop this behavior; thanks for any advice.

**Edit**: This behavior appears only in wired and WiFi modes; in Bluetooth mode this combo only dims backlight.

**Comment by z3ntu** [comment] 2022-06-18 10:20
Duplicate of #579

**Closed as not planned by z3ntu** 2022-06-18 10:20 UTC
Labels: support
