### ISSUE TITLE
Support for Razer Turret for Xbox One

### ISSUE THREAD

**Issue by coltonsteeve** [openrazer/razer-drivers#1884] opened 2022-08-10 18:36 UTC
### Device Info

* Name: Razer Turret for Xbox One Keyboard
* Product Number: RZ03-02820100-0000
* Model Number: RZ03-0282

* Name: Razer Turret for Xbox One Mouse
* Product Number: RZ01-02820100-0000
* Model Number: RZ01-0282

### Device Information

lsusb -d 1532: -v
-----------------
Bus 005 Device 009: ID 1532:0904 Razer USA, Ltd R201-0282 Gaming Keyboard, Mouse Combination [Turret For Xbox One]
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0
  bDeviceSubClass         0
  bDeviceProtocol         0
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0904 R201-0282 Gaming Keyboard, Mouse Combination [Turret For Xbox One]
  bcdDevice            2.00
  iManufacturer           1 Razer
  iProduct                2 Razer Turret Receiver
  iSerial                 0
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors:
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0
      bInterfaceProtocol      1 Keyboard
      iInterface              0
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     179
         Report Descriptors:
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0
      bInterfaceProtocol      2 Mouse
      iInterface              0
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     348
         Report Descriptors:
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0002  1x 2 bytes
        bInterval               1

ls -lah /dev/input/by-id/
-------------------------
lrwxrwxrwx 1 root root  10 Aug 15 18:57 usb-Razer_Razer_Turret_Receiver-event-if01 -> ../event24
lrwxrwxrwx 1 root root  10 Aug 15 18:57 usb-Razer_Razer_Turret_Receiver-event-if02 -> ../event25
lrwxrwxrwx 1 root root   9 Aug 15 18:57 usb-Razer_Razer_Turret_Receiver-event-mouse -> ../event6
lrwxrwxrwx 1 root root   9 Aug 15 18:57 usb-Razer_Razer_Turret_Receiver-if01-event-kbd -> ../event7
lrwxrwxrwx 1 root root   9 Aug 15 18:57 usb-Razer_Razer_Turret_Receiver-mouse -> ../mouse1

### Packet Captures

Haven't been able to get any packet captures yet.

### Synapse Screenshots

<img width="1280" alt="Synapse-Dashboard" src="https://user-images.githubusercontent.com/9199051/185519426-b5e26c24-da6d-4488-9e69-1e22d36537b7.png">
<img width="1280" alt="Synapse-Turret-Keyboard-Customize" src="https://user-images.githubusercontent.com/9199051/185519427-76a39d79-4a6c-42da-8313-63debceea2b1.png">
<img width="1280" alt="Synapse-Turret-Keyboard-Lighting" src="https://user-images.githubusercontent.com/9199051/185519428-23637bec-0149-4c5b-b705-651688e917c7.png">
<img width="1280" alt="Synapse-Turret-Keyboard-Power" src="https://user-images.githubusercontent.com/9199051/185519429-9aed286a-ac72-4321-8d1b-1a9f94394e87.png">
<img width="1280" alt="Synapse-Turret-Mouse-Calibration" src="https://user-images.githubusercontent.com/9199051/185519430-5abe42ce-3c03-4540-b7ba-3c3ea06ebef1.png">
<img width="1280" alt="Synapse-Turret-Mouse-Customize" src="https://user-images.githubusercontent.com/9199051/185519431-a9916661-f271-40b0-bbc0-6ef5d82ab4c9.png">
<img width="1280" alt="Synapse-Turret-Mouse-Lighting" src="https://user-images.githubusercontent.com/9199051/185519432-304b9f99-4ced-4e6c-8d42-2e259c36f3b6.png">
<img width="1280" alt="Synapse-Turret-Mouse-Performance" src="https://user-images.githubusercontent.com/9199051/185519434-6cc0f8f7-f482-4d14-8dc8-fde606eff143.png">
<img width="1280" alt="Synapse-Turret-Mouse-Power" src="https://user-images.githubusercontent.com/9199051/185519436-f9a359ca-9e86-4d29-b5d3-b8595d5667c4.png">

**Comment by z3ntu** [comment] 2022-10-15 16:44
Duplicate of #1060

**Closed as not planned by z3ntu** 2022-10-15 16:44 UTC
Labels: duplicate, Device Support
