### ISSUE TITLE
Support for Razer DeathAdder 2000 (Cynosa Pro Bundle)

### ISSUE THREAD

**Issue by randomzigzag** [openrazer/razer-drivers#1877] opened 2022-08-07 03:15 UTC
### Device Info

* Name: Razer DeathAdder 2000 (Cynosa Pro Bundle)
* Product Number: RZ01-01450600
* Model Number: RZ85-01470200

### Device Information
Please post the output of
    lsusb -d 1532: -v
```
Bus 002 Device 004: ID 1532:004d Razer USA, Ltd DeathAdder 2000 (Cynosa Pro Bundle)
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x004d DeathAdder 2000 (Cynosa Pro Bundle)
  bcdDevice            2.00
  iManufacturer           1 Razer
  iProduct                2 Razer DeathAdder
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0022
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
```
Please post the output of
    ls -lah /dev/input/by-id/
```
total 0
drwxr-xr-x 2 root root 100 Aug  6 20:24 .
drwxr-xr-x 4 root root 540 Aug  6 20:24 ..
lrwxrwxrwx 1 root root  10 Aug  6 20:24 usb-Chicony_Electronics_Co.__Ltd._Integrated_Camera-event-if00 -> ../event18
lrwxrwxrwx 1 root root   9 Aug  6 20:24 usb-Razer_Razer_DeathAdder-event-mouse -> ../event6
lrwxrwxrwx 1 root root   9 Aug  6 20:24 usb-Razer_Razer_DeathAdder-mouse -> ../mouse1
```
### Packet Captures

Probably unnecessary, considering this is just the same mouse as the Razer DeathAdder 2000 but with a different product id.

### Synapse Screenshots

**Comment by z3ntu** [comment] 2022-10-15 16:29
Duplicate of #495

**Closed as not planned by z3ntu** 2022-10-15 16:29 UTC
Labels: duplicate, Device Support
