### ISSUE TITLE
Support for [device name here]

### ISSUE THREAD

**Issue by mayorajesus182** [openrazer/razer-drivers#2138] opened 2023-09-30 16:03 UTC
### Device Info

* Name: RAZER ORNATA V3
* Product Number: <1532:02a1>
* Model Number: RZ03-0446

### Device Information
```
Please post the output of
    lsusb -d 1532: -v
```

```
Please post the output of
    ls -lah /dev/input/by-id/
![image](https://github.com/openrazer/openrazer/assets/31489898/8d79b725-622a-497c-89ef-f73a682f838e)

```

<details>

```
Please post the output of
    usbhid-dump -m 1532 -ed 
![image](https://github.com/openrazer/openrazer/assets/31489898/467ed033-393d-4a70-89c5-8889f2caaf11)

```

</details>

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<Screenshots of all available options as seen on **Razer Synapse** in a Windows Environment>

**Comment by z3ntu** [comment] 2023-09-30 16:15
Duplicate of #2053

**Closed as not planned by z3ntu** 2023-09-30 16:15 UTC
Labels: duplicate, Device Support
