### ISSUE TITLE
Support for [Naga Epic Chroma - 1532:003E]

### ISSUE THREAD

**Issue by JacobWarners** [openrazer/razer-drivers#1607] opened 2021-09-17 19:07 UTC
### Device Info

* Name: <Naga Epic Chroma>
* Product Number: <1532:003E>
* Model Number: < RZ01-01610100> (This may be wrong?)

### Device Information
```
Please post the output of
    lsusb -d 1532: -v
ID 1532:003e Razer USA, Ltd Naga Epic Chroma (Wired)
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x003e Naga Epic Chroma (Wired)
  bcdDevice            2.00
  iManufacturer           1 Razer
  iProduct                2 Razer Naga Epic Chroma
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
Device Status:     0x0000
  (Bus Powered)
```

```
Please post the output of
    ls -lah /dev/input/by-id/

lrwxrwxrwx 1 root root  10 Sep 17 11:24 usb-Razer_Razer_Naga_Epic_Chroma-event-if02 -> ../event19
lrwxrwxrwx 1 root root  10 Sep 17 11:24 usb-Razer_Razer_Naga_Epic_Chroma-event-mouse -> ../event16
lrwxrwxrwx 1 root root  10 Sep 17 11:24 usb-Razer_Razer_Naga_Epic_Chroma-if01-event-kbd -> ../event17
lrwxrwxrwx 1 root root  10 Sep 17 11:24 usb-Razer_Razer_Naga_Epic_Chroma-if02-event-kbd -> ../event18
lrwxrwxrwx 1 root root   9 Sep 17 11:24 usb-Razer_Razer_Naga_Epic_Chroma-mouse -> ../mouse1
```

### Packet Captures
Can get them, but don't have synapse which may been needed. I'll have to do the VM with a windows thing let me know.

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
Don't have Synapse installed
<Screenshots of all available options as seen on Razer Synapse>

**Comment by z3ntu** [comment] 2021-10-01 20:07
Duplicate of #299

**Closed as completed by z3ntu** 2021-10-01 20:07 UTC
Labels: duplicate, Device Support
