### ISSUE TITLE
Support for Razer Naga V2 Pro (wireless 2.4)

### ISSUE THREAD

**Issue by fiercebrake** [openrazer/razer-drivers#1986] opened 2022-12-20 13:42 UTC
### Device Info

* Name: Razer Naga V2 Pro
* Product Number: rz01-0440100
* Model Number: rz01-0440

### Device Information
```
```
[ls.txt](https://github.com/openrazer/openrazer/files/10268824/ls.txt)
[lsusb.txt](https://github.com/openrazer/openrazer/files/10268898/lsusb.txt)

```

```

<details>

```
```
[usbhid-dump.txt](https://github.com/openrazer/openrazer/files/10268863/usbhid-dump.txt)
</details>

**Comment by z3ntu** [comment] 2022-12-20 14:11
Duplicate of #1952

**Closed as not planned by z3ntu** 2022-12-20 14:11 UTC
Labels: duplicate, Device Support
