### ISSUE TITLE
Support for 1532:0268 - razer blade 15 base model 2020

### ISSUE THREAD

**Issue by cogtoto** [openrazer/razer-drivers#1608] opened 2021-09-19 10:36 UTC
### Device Information
1532:0268 - razer blade 15 base model 2020
product no : RZ09-03519F11

### Please post the output of
    lsusb -d 1532: -v
Bus 001 Device 003: ID 1532:0268 Razer USA, Ltd Razer Blade
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0
  bDeviceSubClass         0
  bDeviceProtocol         0
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0268
  bcdDevice            2.00
  iManufacturer           1 Razer
  iProduct                2 Razer Blade
  iSerial                 0
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors:
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0
      bInterfaceProtocol      1 Keyboard
      iInterface              0
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors:
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0
      bInterfaceProtocol      2 Mouse
      iInterface              0
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors:
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
can't get device qualifier: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
Device Status:     0x0000
  (Bus Powered)
```
ls -lah /dev/input/by-id/
total 0
drwxr-xr-x 2 root root 160 sept. 19 12:20 .
drwxr-xr-x 4 root root 660 sept. 19 12:20 ..
lrwxrwxrwx 1 root root  10 sept. 19 12:20 usb-Chicony_Electronics_Co._Ltd._HD_Webcam_0001-event-if00 -> ../event17
lrwxrwxrwx 1 root root  10 sept. 19 12:20 usb-Razer_Razer_Blade-event-if01 -> ../event12
lrwxrwxrwx 1 root root   9 sept. 19 12:20 usb-Razer_Razer_Blade-event-kbd -> ../event3
lrwxrwxrwx 1 root root   9 sept. 19 12:20 usb-Razer_Razer_Blade-if01-event-kbd -> ../event6
lrwxrwxrwx 1 root root  10 sept. 19 12:20 usb-Razer_Razer_Blade-if02-event-mouse -> ../event16
lrwxrwxrwx 1 root root   9 sept. 19 12:20 usb-Razer_Razer_Blade-if02-mouse -> ../mouse2

```
Thank you
Vincent

**Comment by cogtoto** [comment] 2021-09-22 14:25
![image](https://user-images.githubusercontent.com/77988258/134362243-3f64dcba-69a7-495a-84ae-b6ccbb28af74.png)

**Comment by cogtoto** [comment] 2021-09-22 19:52
open

**Comment by z3ntu** [comment] 2021-10-01 20:18
Duplicate of #1524

**Closed as completed by z3ntu** 2021-10-01 20:18 UTC
Labels: duplicate, Device Support
