### ISSUE TITLE
Mouse Dock Pro

### ISSUE THREAD

**Issue by jtolA138** [openrazer/razer-drivers#2330] opened 2024-10-20 03:05 UTC
### Device Name

Mouse Dock Pro

### Product Number

RZ81-01990100

### Model Number

RC21-019901

### VID:PID

1532:00a4

### USB Details

```shell
Bus 001 Device 017: ID 1532:00cd Razer USA, Ltd Razer Basilisk V3 Pro 35K
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x00cd 
  bcdDevice            1.00
  iManufacturer           1 Razer
  iProduct                2 Razer Basilisk V3 Pro 35K
  iSerial                 3 000000000000
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0086
    bNumInterfaces          5
    bConfigurationValue     1
    iConfiguration          4 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     100
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     314
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        4
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     327
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x85  EP 5 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        3
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     327
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x84  EP 4 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1

Bus 001 Device 011: ID 1532:00a4 Razer USA, Ltd Razer Mouse Dock Pro
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x00a4 
  bcdDevice            1.01
  iManufacturer           1 Razer
  iProduct                2 Razer Mouse Dock Pro
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.00
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.00
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     314
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
```

### Device Input Paths

```shell
total 0
drwxr-xr-x 2 root root 480 Oct 19 22:20 .
drwxr-xr-x 4 root root 960 Oct 19 22:20 ..
lrwxrwxrwx 1 root root  10 Oct 19 21:38 usb-Logitech_USB_Receiver-if01-event-mouse -> ../event10
lrwxrwxrwx 1 root root   9 Oct 19 21:38 usb-Logitech_USB_Receiver-if01-mouse -> ../mouse1
lrwxrwxrwx 1 root root   9 Oct 19 21:38 usb-MSI_MYSTIC_LIGHT_A02021081203-event-if00 -> ../event4
lrwxrwxrwx 1 root root  11 Oct 19 22:20 usb-nuphy_NuPhy_Field75_HE_2023-11-15-event-if01 -> ../event257
lrwxrwxrwx 1 root root  11 Oct 19 22:20 usb-nuphy_NuPhy_Field75_HE_2023-11-15-event-if02 -> ../event258
lrwxrwxrwx 1 root root  11 Oct 19 22:20 usb-nuphy_NuPhy_Field75_HE_2023-11-15-event-kbd -> ../event256
lrwxrwxrwx 1 root root  11 Oct 19 22:20 usb-nuphy_NuPhy_Field75_HE_2023-11-15-if02-event-mouse -> ../event259
lrwxrwxrwx 1 root root   9 Oct 19 22:20 usb-nuphy_NuPhy_Field75_HE_2023-11-15-if02-mouse -> ../mouse5
lrwxrwxrwx 1 root root   9 Oct 19 22:18 usb-Razer_Razer_Basilisk_V3_Pro_35K_000000000000-event-if01 -> ../event8
lrwxrwxrwx 1 root root   9 Oct 19 22:18 usb-Razer_Razer_Basilisk_V3_Pro_35K_000000000000-event-mouse -> ../event5
lrwxrwxrwx 1 root root   9 Oct 19 22:18 usb-Razer_Razer_Basilisk_V3_Pro_35K_000000000000-if01-event-kbd -> ../event6
lrwxrwxrwx 1 root root   9 Oct 19 22:18 usb-Razer_Razer_Basilisk_V3_Pro_35K_000000000000-if01-event-mouse -> ../event7
lrwxrwxrwx 1 root root   9 Oct 19 22:18 usb-Razer_Razer_Basilisk_V3_Pro_35K_000000000000-if01-mouse -> ../mouse4
lrwxrwxrwx 1 root root   9 Oct 19 22:18 usb-Razer_Razer_Basilisk_V3_Pro_35K_000000000000-if02-event-kbd -> ../event9
lrwxrwxrwx 1 root root   9 Oct 19 22:18 usb-Razer_Razer_Basilisk_V3_Pro_35K_000000000000-mouse -> ../mouse0
lrwxrwxrwx 1 root root  10 Oct 19 21:52 usb-Razer_Razer_Mouse_Dock_Pro-event-if01 -> ../event30
lrwxrwxrwx 1 root root  10 Oct 19 21:52 usb-Razer_Razer_Mouse_Dock_Pro-event-mouse -> ../event12
lrwxrwxrwx 1 root root  10 Oct 19 21:52 usb-Razer_Razer_Mouse_Dock_Pro-if01-event-kbd -> ../event13
lrwxrwxrwx 1 root root  10 Oct 19 21:52 usb-Razer_Razer_Mouse_Dock_Pro-if01-event-mouse -> ../event29
lrwxrwxrwx 1 root root   9 Oct 19 21:52 usb-Razer_Razer_Mouse_Dock_Pro-if01-mouse -> ../mouse3
lrwxrwxrwx 1 root root  10 Oct 19 21:52 usb-Razer_Razer_Mouse_Dock_Pro-if02-event-kbd -> ../event31
lrwxrwxrwx 1 root root   9 Oct 19 21:52 usb-Razer_Razer_Mouse_Dock_Pro-mouse -> ../mouse2
```

### USB HID Dump

```shell
libusb: error [get_usbfs_fd] libusb couldn't open USB device /dev/bus/usb/001/017, errno=13
libusb: error [get_usbfs_fd] libusb requires write access to USB device nodes
Failed to find and open the devices: Access denied (insufficient permissions)
```

### Synapse Screenshots

![Screenshot from 2024-10-19 23-01-02](https://github.com/user-attachments/assets/dc4783be-e6d7-4155-b9b2-6ba4b56c715b)
![Screenshot from 2024-10-19 23-00-46](https://github.com/user-attachments/assets/866e2262-2934-4d67-aba5-67af7f0f697a)

**Comment by z3ntu** [comment] 2024-10-20 09:56
Duplicate of https://github.com/openrazer/openrazer/issues/2060

**Closed as completed by z3ntu** 2024-10-20 09:56 UTC
Labels: duplicate, Device Support
