### ISSUE TITLE
Support for Tartarus 

### ISSUE THREAD

**Issue by MicHaeL-MonStaR** [openrazer/razer-drivers#2051] opened 2023-04-20 13:19 UTC
### Device Info

* Name: Tartarus Pro
* Product Number: RZ07-03110100
* Model Number: RZ07-0311
### Device Information
```
Bus 002 Device 002: ID 1532:0244 Razer USA, Ltd RZ07-0311 Gaming Keypad [Tartarus Pro]
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0244 RZ07-0311 Gaming Keypad [Tartarus Pro]
  bcdDevice            2.00
  iManufacturer           1 Razer
  iProduct                2 Razer Tartarus Pro
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     186
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0018  1x 24 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1

```

```
total 0
drwxr-xr-x 2 root root 240 Apr 20 09:54 .
drwxr-xr-x 4 root root 620 Apr 20 09:54 ..
lrwxrwxrwx 1 root root   9 Apr 20 09:54 usb-Logitech_Gaming_Mouse_G502_108035493335-event-mouse -> ../event6
lrwxrwxrwx 1 root root   9 Apr 20 09:54 usb-Logitech_Gaming_Mouse_G502_108035493335-if01-event-kbd -> ../event7
lrwxrwxrwx 1 root root   9 Apr 20 09:54 usb-Logitech_Gaming_Mouse_G502_108035493335-mouse -> ../mouse1
lrwxrwxrwx 1 root root   9 Apr 20 09:54 usb-Razer_Razer_Tartarus_Pro-event-if01 -> ../event4
lrwxrwxrwx 1 root root   9 Apr 20 09:54 usb-Razer_Razer_Tartarus_Pro-event-kbd -> ../event2
lrwxrwxrwx 1 root root   9 Apr 20 09:54 usb-Razer_Razer_Tartarus_Pro-if01-event-kbd -> ../event3
lrwxrwxrwx 1 root root   9 Apr 20 09:54 usb-Razer_Razer_Tartarus_Pro-if02-event-mouse -> ../event5
lrwxrwxrwx 1 root root   9 Apr 20 09:54 usb-Razer_Razer_Tartarus_Pro-if02-mouse -> ../mouse0
lrwxrwxrwx 1 root root  10 Apr 20 09:54 usb-SONiX_USB_DEVICE-event-if01 -> ../event10
lrwxrwxrwx 1 root root   9 Apr 20 09:54 usb-SONiX_USB_DEVICE-event-kbd -> ../event8

```

<details>

```
libusb: error [get_usbfs_fd] libusb couldn't open USB device /dev/bus/usb/002/002, errno=13
libusb: error [get_usbfs_fd] libusb requires write access to USB device nodes
Failed to find and open the devices: Access denied (insufficient permissions)
```

</details>

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<Screenshots of all available options as seen on **Razer Synapse** in a Windows Environment>

I don't have a working Windows installation, which is how I ended up here.
It shouldn't be too different from the preceding Tartarus-keypads, as the Pro-version's difference is basically the optical/analog switches.

**Comment by z3ntu** [comment] 2023-04-22 20:32
Duplicate of #1039, see also #1817

**Closed as not planned by z3ntu** 2023-04-22 20:32 UTC
Labels: duplicate, Device Support
