### ISSUE TITLE
Support for Razer Ornata V3 [02a1] (different Ornata V3 version?)

### ISSUE THREAD

**Issue by a1466d44-d3dc-4c0b-90c7-315b088731d7** [openrazer/razer-drivers#2176] opened 2023-12-04 07:26 UTC
### Device Info

* Name: Razer Ornata V3
* Product Number: RZ03-04460400-R3G1
* Model Number: RZ03-0446

### Device Information

Please post the output of
    lsusb -d 1532: -v
```
Bus 001 Device 005: ID 1532:02a1 Razer USA, Ltd Razer Ornata V3
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 [unknown]
  bDeviceSubClass         0 [unknown]
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x02a1 Razer Ornata V3
  bcdDevice            2.00
  iManufacturer           1 Razer
  iProduct                2 Razer Ornata V3
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
          Report Descriptors: 
            ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 [unknown]
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     179
          Report Descriptors: 
            ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0016  1x 22 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 [unknown]
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
          Report Descriptors: 
            ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
```
Please post the output of
    ls -lah /dev/input/by-id/
```
drwxr-xr-x 2 root root 200 Dec  2 15:44 .
drwxr-xr-x 4 root root 420 Dec  2 15:44 ..
lrwxrwxrwx 1 root root   9 Dec  2 15:38 usb-La-VIEW_Technology_SteelSeries-event-mouse -> ../event7
lrwxrwxrwx 1 root root   9 Dec  2 15:38 usb-La-VIEW_Technology_SteelSeries-if01-event-kbd -> ../event8
lrwxrwxrwx 1 root root   9 Dec  2 15:38 usb-La-VIEW_Technology_SteelSeries-mouse -> ../mouse1
lrwxrwxrwx 1 root root   9 Dec  2 15:44 usb-Razer_Razer_Ornata_V3-event-if01 -> ../event5
lrwxrwxrwx 1 root root   9 Dec  2 15:44 usb-Razer_Razer_Ornata_V3-event-kbd -> ../event3
lrwxrwxrwx 1 root root   9 Dec  2 15:44 usb-Razer_Razer_Ornata_V3-if01-event-kbd -> ../event4
lrwxrwxrwx 1 root root   9 Dec  2 15:44 usb-Razer_Razer_Ornata_V3-if02-event-mouse -> ../event6
lrwxrwxrwx 1 root root   9 Dec  2 15:44 usb-Razer_Razer_Ornata_V3-if02-mouse -> ../mouse0

```
Please post the output of
    usbhid-dump -m 1532 -ed
```
001:005:002:DESCRIPTOR         1701674634.694042
 05 01 09 02 A1 01 09 01 A1 00 05 09 19 01 29 05
 15 00 25 01 75 01 95 05 81 02 75 01 95 03 81 03
 06 00 FF 09 40 75 08 95 02 15 81 25 7F 81 02 05
 01 09 38 15 81 25 7F 75 08 95 01 81 06 09 30 09
 31 16 00 80 26 FF 7F 75 10 95 02 81 06 C0 06 00
 FF 09 02 15 00 25 01 75 08 95 5A B1 01 C0

001:005:001:DESCRIPTOR         1701674634.694641
 05 01 09 06 A1 01 85 01 05 07 05 07 19 E0 29 E7
 15 00 25 01 75 01 95 08 81 02 19 00 29 A0 15 00
 25 01 75 01 95 A0 81 02 05 08 19 01 29 03 15 00
 25 01 75 01 95 03 91 02 95 05 91 01 C0 05 0C 09
 01 A1 01 85 02 19 00 2A 3C 02 15 00 26 3C 02 95
 01 75 10 81 00 75 08 95 13 81 01 C0 05 01 09 80
 A1 01 85 03 19 81 29 83 15 00 25 01 75 01 95 03
 81 02 95 05 81 01 75 08 95 14 81 01 C0 05 01 09
 00 A1 01 85 04 09 03 15 00 26 FF 00 35 00 46 FF
 00 75 08 95 15 81 00 C0 05 01 09 00 A1 01 85 05
 09 03 15 00 26 FF 00 35 00 46 FF 00 75 08 95 15
 81 00 C0

001:005:000:DESCRIPTOR         1701674634.695063
 05 01 09 06 A1 01 05 07 19 E0 29 E7 15 00 25 01
 75 01 95 08 81 02 81 01 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 06 81 00 05 08 19 01 29 03 15 00
 25 01 75 01 95 03 91 02 95 05 91 01 C0

```
</details>

### Packet Captures

I cant provide any as I have no Windows Machine at the moment...

### Synapse Screenshots
Same as for the packet capture...

**Comment by z3ntu** [comment] 2023-12-04 12:12
Duplicate of #2053

**Closed as not planned by z3ntu** 2023-12-04 12:12 UTC
Labels: duplicate, Device Support

**Comment by a1466d44-d3dc-4c0b-90c7-315b088731d7** [comment] 2023-12-04 13:29
ahh, sorry. Overlooked that...
PS.: There was a discount of this model about 2 to 3 Weeks ago in Austria. So may bee a few more people own one of those now (like myself) :)
