### ISSUE TITLE
Support for [Cynosa Pro Bundle]

### ISSUE THREAD

**Issue by g0lr** [openrazer/razer-drivers#1611] opened 2021-09-21 20:56 UTC
### Device Info

* Name: ID:  Cynosa Pro Bundle (DeathAdder 2000 / Cynosa Pro keyboard)
* Product Number: 1532:004d  / 1532:020d
* Model Number: <See under device>

### Device Information

Please post the output of
    lsusb -d 1532: -v
```
Bus 003 Device 005: ID 1532:004d Razer USA, Ltd DeathAdder 2000 (Cynosa Pro Bundle)
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x004d DeathAdder 2000 (Cynosa Pro Bundle)
  bcdDevice            2.00
  iManufacturer           1 Razer
  iProduct                2 Razer DeathAdder
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0022
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
Device Status:     0x0000
  (Bus Powered)

Bus 001 Device 050: ID 1532:020d Razer USA, Ltd Cynosa Pro keyboard (Cynosa Pro Bundle)
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x020d Cynosa Pro keyboard (Cynosa Pro Bundle)
  bcdDevice            2.00
  iManufacturer           1 Razer
  iProduct                2 Razer Cynosa Pro Bundle
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
Device Status:     0x0000
  (Bus Powered)
                 
```
Please post the output of
    ls -lah /dev/input/by-id/
```
rwxrwxrwx 1 root root   9 Sep 21 15:41 usb-Azurewave_HD_Camera_0x0001-event-if00 -> ../event6
lrwxrwxrwx 1 root root  10 Sep 21 15:56 usb-Razer_Razer_Cynosa_Pro_Bundle-event-if01 -> ../event11
lrwxrwxrwx 1 root root   9 Sep 21 15:56 usb-Razer_Razer_Cynosa_Pro_Bundle-event-kbd -> ../event8
lrwxrwxrwx 1 root root   9 Sep 21 15:56 usb-Razer_Razer_Cynosa_Pro_Bundle-if01-event-kbd -> ../event9
lrwxrwxrwx 1 root root  10 Sep 21 15:56 usb-Razer_Razer_Cynosa_Pro_Bundle-if02-event-mouse -> ../event13
lrwxrwxrwx 1 root root   9 Sep 21 15:56 usb-Razer_Razer_Cynosa_Pro_Bundle-if02-mouse -> ../mouse3
lrwxrwxrwx 1 root root  10 Sep 21 15:55 usb-Razer_Razer_DeathAdder-event-mouse -> ../event14
lrwxrwxrwx 1 root root   9 Sep 21 15:55 usb-Razer_Razer_DeathAdder-mouse -> ../mouse4
```

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<Screenshots of all available options as seen on Razer Synapse>

**Comment by z3ntu** [comment] 2021-10-01 20:14
Duplicate of #495

**Closed as completed by z3ntu** 2021-10-01 20:14 UTC
Labels: duplicate, Device Support
