### ISSUE TITLE
Support for razer naga molten (special edition)

### ISSUE THREAD

**Issue by Jimbito** [openrazer/razer-drivers#1745] opened 2022-02-06 21:08 UTC
### Device Info

* Name: <razer naga molten special edition>
* Product Number: <RZ01-00280500>
* Model Number: <RZ01-0028, Laser Gaming Mouse>

### Device Information
```
Please post the output of
    lsusb -d 1532: -v
```
Bus 001 Device 002: ID 1532:0015 Razer USA, Ltd Naga Mouse
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0         8
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0015 Naga Mouse
  bcdDevice            2.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x003b
    bNumInterfaces          2
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      93
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      47
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0009  1x 9 bytes
        bInterval               1

```
Please post the output of
    ls -lah /dev/input/by-id/


total 0
drwxr-xr-x 2 root root 120 Feb  6 21:02 .
drwxr-xr-x 4 root root 640 Feb  6 21:02 ..
lrwxrwxrwx 1 root root   9 Feb  6 21:02 usb-CN0HK46K8LG0008DHTKKA02_Integrated_Webcam_HD_200901010001-event-if00 -> ../event5
lrwxrwxrwx 1 root root   9 Feb  6 21:02 usb-Razer_Razer_Naga-event-mouse -> ../event7
lrwxrwxrwx 1 root root   9 Feb  6 21:02 usb-Razer_Razer_Naga-if01-event-kbd -> ../event8
lrwxrwxrwx 1 root root   9 Feb  6 21:02 usb-Razer_Razer_Naga-mouse -> ../mouse3

```

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots

<Screenshots of all available options as seen on **Razer Synapse** in a Windows Environment>

**Comment by z3ntu** [comment] 2022-02-19 19:40
Duplicate of #139

**Closed as completed by z3ntu** 2022-02-19 19:40 UTC
Labels: duplicate, Device Support
