### ISSUE TITLE
Support for Core X Chroma (eGPU Case)

### ISSUE THREAD

**Issue by KPKoch** [openrazer/razer-drivers#1660] opened 2021-11-08 23:29 UTC
### Device Info

* Name: Razor Core X Chroma
* Product Number: RC21-01430100-R351
* Model Number: <See under device>

### Device Information
```
Please post the output of
    lsusb -d 1532: -v

Bus 007 Device 002: ID 1532:0f1a Razer USA, Ltd Core X Chroma
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0f1a Core X Chroma
  bcdDevice            2.00
  iManufacturer           1 Razer
  iProduct                2 Razer Core X Chroma
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
Device Status:     0x0000
  (Bus Powered)

```

```

    ls -lah /dev/input/by-id/

drwxr-xr-x 2 root root 360  9. Nov 00:08 .
drwxr-xr-x 4 root root 880  9. Nov 00:08 ..
lrwxrwxrwx 1 root root  11  9. Nov 00:08 usb-Elgato_Cam_Link_4K_0005AC7166000-event-if00 -> ../event256
lrwxrwxrwx 1 root root   9  9. Nov 00:08 usb-Logitech_Gaming_Mouse_G502_0D8C36593132-event-mouse -> ../event8
lrwxrwxrwx 1 root root   9  9. Nov 00:08 usb-Logitech_Gaming_Mouse_G502_0D8C36593132-if01-event-kbd -> ../event9
lrwxrwxrwx 1 root root   9  9. Nov 00:08 usb-Logitech_Gaming_Mouse_G502_0D8C36593132-mouse -> ../mouse1
lrwxrwxrwx 1 root root  10  9. Nov 00:08 usb-Microsoft_Microsoft®_2.4GHz_Transceiver_v9.0-event-if01 -> ../event12
lrwxrwxrwx 1 root root  10  9. Nov 00:08 usb-Microsoft_Microsoft®_2.4GHz_Transceiver_v9.0-event-if02 -> ../event14
lrwxrwxrwx 1 root root  10  9. Nov 00:08 usb-Microsoft_Microsoft®_2.4GHz_Transceiver_v9.0-event-kbd -> ../event10
lrwxrwxrwx 1 root root  10  9. Nov 00:08 usb-Microsoft_Microsoft®_2.4GHz_Transceiver_v9.0-if01-event-mouse -> ../event11
lrwxrwxrwx 1 root root   9  9. Nov 00:08 usb-Microsoft_Microsoft®_2.4GHz_Transceiver_v9.0-if01-mouse -> ../mouse2
lrwxrwxrwx 1 root root  10  9. Nov 00:08 usb-Microsoft_Microsoft®_2.4GHz_Transceiver_v9.0-if02-event-kbd -> ../event13
lrwxrwxrwx 1 root root   9  9. Nov 00:08 usb-Razer_Razer_Core_X_Chroma-event-if01 -> ../event6
lrwxrwxrwx 1 root root   9  9. Nov 00:08 usb-Razer_Razer_Core_X_Chroma-event-kbd -> ../event4
lrwxrwxrwx 1 root root   9  9. Nov 00:08 usb-Razer_Razer_Core_X_Chroma-if01-event-kbd -> ../event5
lrwxrwxrwx 1 root root   9  9. Nov 00:08 usb-Razer_Razer_Core_X_Chroma-if02-event-mouse -> ../event7
lrwxrwxrwx 1 root root   9  9. Nov 00:08 usb-Razer_Razer_Core_X_Chroma-if02-mouse -> ../mouse0
lrwxrwxrwx 1 root root  10  9. Nov 00:08 usb-RODE_Microphones_RODE_NT-USB-event-if03 -> ../event15


```

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<Screenshots of all available options as seen on Razer Synapse>
Don't have a windows available. 

Even if I could fill in all information, I hope it is sufficient.

**Comment by z3ntu** [comment] 2021-12-03 16:56
Duplicate of #929

**Closed as completed by z3ntu** 2021-12-03 16:56 UTC
Labels: duplicate, Device Support
