### ISSUE TITLE
Support for [Laptop Stand Chroma V2]

### ISSUE THREAD

**Issue by Unless0215** [openrazer/razer-drivers#2129] opened 2023-09-16 18:25 UTC
### Device Info

* Name: Razer Laptop Stand Chroma V2
* Product Number: 
* Model Number: RC21-0168

### Device Information
```
Please post the output of
    lsusb -d 1532: -v

Bus 001 Device 016: ID 1532:0f2b Razer USA, Ltd Razer Laptop Stand Chroma V2
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0f2b 
  bcdDevice            2.00
  iManufacturer           1 Razer
  iProduct                2 Razer Laptop Stand Chroma V2
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1

```

```
Please post the output of
    ls -lah /dev/input/by-id/

rwxrwxrwx 1 root root   9 Sep 15 17:11 usb-Razer_Razer_BlackWidow_V4_Pro-event-if01 -> ../event9
lrwxrwxrwx 1 root root  10 Sep 15 17:11 usb-Razer_Razer_BlackWidow_V4_Pro-event-if04 -> ../event11
lrwxrwxrwx 1 root root   9 Sep 15 17:11 usb-Razer_Razer_BlackWidow_V4_Pro-event-kbd -> ../event7
lrwxrwxrwx 1 root root   9 Sep 15 17:11 usb-Razer_Razer_BlackWidow_V4_Pro-if01-event-kbd -> ../event8
lrwxrwxrwx 1 root root  10 Sep 15 17:11 usb-Razer_Razer_BlackWidow_V4_Pro-if02-event-mouse -> ../event10
lrwxrwxrwx 1 root root   9 Sep 15 17:11 usb-Razer_Razer_BlackWidow_V4_Pro-if02-mouse -> ../mouse1
lrwxrwxrwx 1 root root  10 Sep 15 17:11 usb-Razer_Razer_Blade-event-kbd -> ../event12
lrwxrwxrwx 1 root root  10 Sep 15 17:11 usb-Razer_Razer_Blade-if01-event-kbd -> ../event15
lrwxrwxrwx 1 root root  10 Sep 15 17:11 usb-Razer_Razer_Blade-if02-event-mouse -> ../event16
lrwxrwxrwx 1 root root   9 Sep 15 17:11 usb-Razer_Razer_Blade-if02-mouse -> ../mouse2
lrwxrwxrwx 1 root root   9 Sep 15 17:11 usb-Razer_Razer_DeathAdder_V2-event-mouse -> ../event3
lrwxrwxrwx 1 root root   9 Sep 15 17:11 usb-Razer_Razer_DeathAdder_V2-if01-event-kbd -> ../event6
lrwxrwxrwx 1 root root   9 Sep 15 17:11 usb-Razer_Razer_DeathAdder_V2-if02-event-kbd -> ../event4
lrwxrwxrwx 1 root root   9 Sep 15 17:11 usb-Razer_Razer_DeathAdder_V2-mouse -> ../mouse0
lrwxrwxrwx 1 root root   9 Sep 16 14:20 usb-Razer_Razer_Goliathus_Chroma-event-mouse -> ../event5
lrwxrwxrwx 1 root root  10 Sep 16 14:20 usb-Razer_Razer_Goliathus_Chroma-if01-event-kbd -> ../event13
lrwxrwxrwx 1 root root  10 Sep 16 14:20 usb-Razer_Razer_Goliathus_Chroma-if02-event-kbd -> ../event14
lrwxrwxrwx 1 root root   9 Sep 16 14:20 usb-Razer_Razer_Goliathus_Chroma-mouse -> ../mouse5
lrwxrwxrwx 1 root root  10 Sep 15 17:11 usb-Razer_Razer_Kraken_Ultimate_00000000-event-if03 -> ../event28
lrwxrwxrwx 1 root root  11 Sep 16 14:20 usb-Razer_Razer_Laptop_Stand_Chroma_V2-event-if01 -> ../event258
lrwxrwxrwx 1 root root  10 Sep 16 14:20 usb-Razer_Razer_Laptop_Stand_Chroma_V2-event-mouse -> ../event17
lrwxrwxrwx 1 root root  11 Sep 16 14:20 usb-Razer_Razer_Laptop_Stand_Chroma_V2-if01-event-kbd -> ../event257
lrwxrwxrwx 1 root root  11 Sep 16 14:20 usb-Razer_Razer_Laptop_Stand_Chroma_V2-if02-event-kbd -> ../event259
lrwxrwxrwx 1 root root   9 Sep 16 14:20 usb-Razer_Razer_Laptop_Stand_Chroma_V2-mouse -> ../mouse6

```

<details>

```
Please post the output of
    usbhid-dump -m 1532 -ed

001:007:002:DESCRIPTOR         1694888698.379862
 05 01 09 02 A1 01 09 01 A1 00 05 09 19 01 29 05
 15 00 25 01 75 01 95 05 81 02 75 01 95 03 81 03
 06 00 FF 09 40 75 08 95 02 15 81 25 7F 81 02 05
 01 09 38 15 81 25 7F 75 08 95 01 81 06 09 30 09
 31 16 00 80 26 FF 7F 75 10 95 02 81 06 C0 06 00
 FF 09 02 15 00 25 01 75 08 95 5A B1 01 C0

001:007:001:DESCRIPTOR         1694888698.380735
 05 01 09 06 A1 01 85 01 05 07 19 E0 29 E7 15 00
 25 01 75 01 95 08 81 02 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 0E 81 00 C0 05 0C 09 01 A1 01 85
 02 19 00 2A 3C 02 15 00 26 3C 02 95 01 75 10 81
 00 75 08 95 0D 81 01 C0 05 01 09 80 A1 01 85 03
 19 81 29 83 15 00 25 01 75 01 95 03 81 02 95 05
 81 01 75 08 95 0E 81 01 C0 05 01 09 00 A1 01 85
 04 09 03 15 00 26 FF 00 35 00 46 FF 00 75 08 95
 0F 81 00 C0 05 01 09 00 A1 01 85 05 09 03 15 00
 26 FF 00 35 00 46 FF 00 75 08 95 0F 81 00 C0

001:007:000:DESCRIPTOR         1694888698.381782
 05 01 09 06 A1 01 05 07 19 E0 29 E7 15 00 25 01
 75 01 95 08 81 02 81 01 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 06 81 00 05 08 19 01 29 03 15 00
 25 01 75 01 95 03 91 02 95 05 91 01 C0

001:006:003:DESCRIPTOR         1694888698.512755
 05 0C 09 01 A1 01 85 01 15 00 25 01 75 01 09 E9
 09 EA 95 02 81 06 95 06 81 01 85 02 05 0C 09 00
 95 10 81 02 85 04 09 00 75 08 95 24 91 02 85 05
 09 00 95 20 81 02 85 06 09 00 95 24 91 02 85 30
 09 00 95 0F 81 02 85 31 09 00 95 10 91 02 85 32
 09 00 95 01 91 02 85 40 09 00 75 08 95 08 91 02
 85 41 09 00 75 08 95 08 81 02 85 50 09 00 75 08
 95 08 91 02 85 07 09 00 95 20 81 02 C0 05 0B 09
 05 A1 01 85 08 09 00 95 01 81 02 85 0A 15 00 25
 01 09 2F 75 01 95 01 81 06 09 20 09 21 75 01 95
 02 81 22 95 05 81 01 05 08 85 09 09 09 75 01 95
 01 91 22 95 07 91 01 85 17 09 17 75 01 95 01 91
 22 95 07 91 01 85 21 09 21 75 01 95 01 91 22 95
 07 91 01 85 1A 09 18 75 01 95 01 91 22 95 07 91
 01 C0 06 A0 FF 09 01 A1 01 85 23 09 AA 75 08 95
 28 B1 02 C0

001:003:004:DESCRIPTOR         1694888698.514484
 05 59 09 01 A1 01 85 01 09 02 A1 02 09 03 15 00
 27 FF FF 00 00 75 10 95 01 B1 03 09 04 09 05 09
 06 09 07 09 08 15 00 27 FF FF FF 7F 75 20 95 05
 B1 03 C0 85 02 09 20 A1 02 09 21 15 00 27 FF FF
 00 00 75 10 95 01 B1 02 C0 85 03 09 22 A1 02 09
 21 15 00 27 FF FF 00 00 75 10 95 01 B1 02 09 23
 09 24 09 25 09 27 09 26 15 00 27 FF FF FF 7F 75
 20 95 05 B1 02 09 28 09 29 09 2A 09 2C 09 2D 15
 00 26 FF 00 75 08 95 05 B1 02 C0 85 04 09 50 A1
 02 09 03 09 55 15 00 25 08 75 08 95 02 B1 02 09
 21 15 00 27 FF FF 00 00 75 10 95 08 B1 02 09 51
 09 52 09 53 09 51 09 52 09 53 09 51 09 52 09 53
 09 51 09 52 09 53 09 51 09 52 09 53 09 51 09 52
 09 53 09 51 09 52 09 53 09 51 09 52 09 53 15 00
 26 FF 00 75 08 95 18 B1 02 C0 85 05 09 60 A1 02
 09 55 15 00 25 08 75 08 95 01 B1 02 09 61 09 62
 15 00 27 FF FF 00 00 75 10 95 02 B1 02 09 51 09
 52 09 53 15 00 26 FF 00 75 08 95 03 B1 02 C0 85
 06 09 70 A1 02 09 71 15 00 25 01 75 08 95 01 B1
 02 C0 85 07 06 00 FF 15 00 26 FF 00 09 02 75 08
 95 3F B1 02 C0 05 0C 09 01 A1 01 85 08 19 D0 29
 D7 15 00 25 01 75 01 95 08 81 02 C0

001:003:003:DESCRIPTOR         1694888698.516630
 05 01 09 00 A1 01 06 00 FF 09 03 15 00 25 01 75
 08 95 5A B1 01 C0

001:003:002:DESCRIPTOR         1694888698.516941
 05 01 09 02 A1 01 09 01 A1 00 05 09 19 01 29 05
 15 00 25 01 75 01 95 05 81 02 75 01 95 03 81 03
 06 00 FF 75 08 95 01 81 03 05 0C 0A 38 02 15 81
 25 7F 75 08 95 01 81 06 05 01 09 38 15 81 25 7F
 75 08 95 01 81 06 09 30 09 31 16 00 80 26 FF 7F
 75 10 95 02 81 06 C0 C0

001:003:001:DESCRIPTOR         1694888698.517573
 05 01 09 06 A1 01 85 01 05 07 19 E0 29 E7 15 00
 25 01 75 01 95 08 81 02 19 00 29 A0 15 00 25 01
 75 01 95 A0 81 02 05 08 19 01 29 03 15 00 25 01
 75 01 95 03 91 02 95 05 91 01 C0 05 0C 09 01 A1
 01 85 02 19 00 2A 3C 02 15 00 26 3C 02 95 01 75
 10 81 00 75 08 95 13 81 01 C0 05 01 09 80 A1 01
 85 03 19 81 29 83 15 00 25 01 75 01 95 03 81 02
 95 05 81 01 75 08 95 14 81 01 C0 05 01 09 00 A1
 01 85 04 09 03 15 00 26 FF 00 35 00 46 FF 00 75
 08 95 15 81 00 C0 05 01 09 00 A1 01 85 05 09 03
 15 00 26 FF 00 35 00 46 FF 00 75 08 95 15 81 00
 C0

001:003:000:DESCRIPTOR         1694888698.518655
 05 01 09 06 A1 01 05 07 19 E0 29 E7 15 00 25 01
 75 01 95 08 81 02 81 01 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 06 81 00 05 08 19 01 29 03 15 00
 25 01 75 01 95 03 91 02 95 05 91 01 C0

001:019:002:DESCRIPTOR         1694888698.519302
 05 01 09 06 A1 01 05 07 19 E0 29 E7 15 00 25 01
 75 01 95 08 81 02 81 01 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 06 81 00 05 08 19 01 29 03 15 00
 25 01 75 01 95 03 91 02 95 05 91 01 C0

001:019:001:DESCRIPTOR         1694888698.520115
 05 01 09 06 A1 01 85 01 05 07 19 E0 29 E7 15 00
 25 01 75 01 95 08 81 02 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 0E 81 00 C0 05 0C 09 01 A1 01 85
 02 19 00 2A 3C 02 15 00 26 3C 02 95 01 75 10 81
 00 75 08 95 0D 81 01 C0 05 01 09 80 A1 01 85 03
 19 81 29 83 15 00 25 01 75 01 95 03 81 02 95 05
 81 01 75 08 95 0E 81 01 C0 05 01 09 00 A1 01 85
 04 09 03 15 00 26 FF 00 35 00 46 FF 00 75 08 95
 0F 81 00 C0 05 01 09 00 A1 01 85 05 09 03 15 00
 26 FF 00 35 00 46 FF 00 75 08 95 0F 81 00 C0

001:019:000:DESCRIPTOR         1694888698.521271
 05 01 09 02 A1 01 09 01 A1 00 05 09 19 01 29 05
 15 00 25 01 75 01 95 05 81 02 75 01 95 03 81 03
 06 00 FF 09 40 75 08 95 02 15 81 25 7F 81 02 05
 01 09 38 15 81 25 7F 75 08 95 01 81 06 09 30 09
 31 16 00 80 26 FF 7F 75 10 95 02 81 06 C0 06 00
 FF 09 02 15 00 25 01 75 08 95 5A B1 01 C0

001:018:002:DESCRIPTOR         1694888698.522039
 05 01 09 06 A1 01 05 07 19 E0 29 E7 15 00 25 01
 75 01 95 08 81 02 81 01 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 06 81 00 05 08 19 01 29 03 15 00
 25 01 75 01 95 03 91 02 95 05 91 01 C0

001:018:001:DESCRIPTOR         1694888698.522799
 05 01 09 06 A1 01 85 01 05 07 19 E0 29 E7 15 00
 25 01 75 01 95 08 81 02 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 0E 81 00 C0 05 0C 09 01 A1 01 85
 02 19 00 2A 3C 02 15 00 26 3C 02 95 01 75 10 81
 00 75 08 95 0D 81 01 C0 05 01 09 80 A1 01 85 03
 19 81 29 83 15 00 25 01 75 01 95 03 81 02 95 05
 81 01 75 08 95 0E 81 01 C0 05 01 09 00 A1 01 85
 04 09 03 15 00 26 FF 00 35 00 46 FF 00 75 08 95
 0F 81 00 C0 05 01 09 00 A1 01 85 05 09 03 15 00
 26 FF 00 35 00 46 FF 00 75 08 95 0F 81 00 C0

001:018:000:DESCRIPTOR         1694888698.523935
 05 01 09 02 A1 01 09 01 A1 00 05 09 19 01 29 05
 15 00 25 01 75 01 95 05 81 02 75 01 95 03 81 03
 06 00 FF 09 40 75 08 95 02 15 81 25 7F 81 02 05
 01 09 38 15 81 25 7F 75 08 95 01 81 06 09 30 09
 31 16 00 80 26 FF 7F 75 10 95 02 81 06 C0 06 00
 FF 09 02 15 00 25 01 75 08 95 5A B1 01 C0

001:002:003:DESCRIPTOR         1694888698.524943
 05 59 09 01 A1 01 85 01 09 02 A1 02 09 03 15 00
 27 FF FF 00 00 75 10 95 01 B1 03 09 04 09 05 09
 06 09 07 09 08 15 00 27 FF FF FF 7F 75 20 95 05
 B1 03 C0 85 02 09 20 A1 02 09 21 15 00 27 FF FF
 00 00 75 10 95 01 B1 02 C0 85 03 09 22 A1 02 09
 21 15 00 27 FF FF 00 00 75 10 95 01 B1 02 09 23
 09 24 09 25 09 27 09 26 15 00 27 FF FF FF 7F 75
 20 95 05 B1 02 09 28 09 29 09 2A 09 2C 09 2D 15
 00 26 FF 00 75 08 95 05 B1 02 C0 85 04 09 50 A1
 02 09 03 09 55 15 00 25 08 75 08 95 02 B1 02 09
 21 15 00 27 FF FF 00 00 75 10 95 08 B1 02 09 51
 09 52 09 53 09 51 09 52 09 53 09 51 09 52 09 53
 09 51 09 52 09 53 09 51 09 52 09 53 09 51 09 52
 09 53 09 51 09 52 09 53 09 51 09 52 09 53 15 00
 26 FF 00 75 08 95 18 B1 02 C0 85 05 09 60 A1 02
 09 55 15 00 25 08 75 08 95 01 B1 02 09 61 09 62
 15 00 27 FF FF 00 00 75 10 95 02 B1 02 09 51 09
 52 09 53 15 00 26 FF 00 75 08 95 03 B1 02 C0 85
 06 09 70 A1 02 09 71 15 00 25 01 75 08 95 01 B1
 02 C0 85 07 06 00 FF 15 00 26 FF 00 09 02 75 08
 95 3F B1 02 C0

001:002:002:DESCRIPTOR         1694888698.526865
 05 01 09 06 A1 01 05 07 19 E0 29 E7 15 00 25 01
 75 01 95 08 81 02 81 01 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 06 81 00 05 08 19 01 29 03 15 00
 25 01 75 01 95 03 91 02 95 05 91 01 C0

001:002:001:DESCRIPTOR         1694888698.527522
 05 01 09 06 A1 01 85 01 05 07 19 E0 29 E7 15 00
 25 01 75 01 95 08 81 02 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 0E 81 00 C0 05 0C 09 01 A1 01 85
 02 19 00 2A 3C 02 15 00 26 3C 02 95 01 75 10 81
 00 75 08 95 0D 81 01 C0 05 01 09 80 A1 01 85 03
 19 81 29 83 15 00 25 01 75 01 95 03 81 02 95 05
 81 01 75 08 95 0E 81 01 C0 05 01 09 00 A1 01 85
 04 09 03 15 00 26 FF 00 35 00 46 FF 00 75 08 95
 0F 81 00 C0 05 01 09 00 A1 01 85 05 09 03 15 00
 26 FF 00 35 00 46 FF 00 75 08 95 0F 81 00 C0

001:002:000:DESCRIPTOR         1694888698.528633
 05 01 09 02 A1 01 09 01 A1 00 05 09 19 01 29 05
 15 00 25 01 75 01 95 05 81 02 75 01 95 03 81 03
 06 00 FF 09 40 75 08 95 02 15 81 25 7F 81 02 05
 01 09 38 15 81 25 7F 75 08 95 01 81 06 09 30 09
 31 16 00 80 26 FF 7F 75 10 95 02 81 06 C0 06 00
 FF 09 02 15 00 25 01 75 08 95 5A B1 01 C0

```

</details>

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<Screenshots of all available options as seen on **Razer Synapse** in a Windows Environment>

**Comment by Unless0215** [comment] 2023-09-16 18:36
Sorry if there's anything missing here, my very first post on GitHub, let me know if there's any way I can help.

**Comment by z3ntu** [comment] 2023-09-21 21:48
Duplicate of #1730, supported since #1840. This will be included in the next release. Until then you can install e.g. the daily packages on Ubuntu or build from source on other distros.

**Closed as not planned by z3ntu** 2023-09-21 21:48 UTC
Labels: duplicate, Device Support
