### ISSUE TITLE
support request for Ornata V3 X

### ISSUE THREAD

**Issue by dcxbutcher615** [openrazer/razer-drivers#1886] opened 2022-08-12 22:39 UTC
Love this keyboard but would like it at it full potential!
doesn't recognize the Ornata V3 X. Please add it!!!!

**Comment by dcxbutcher615** [comment] 2022-08-12 22:41
1532:0294

**Comment by z3ntu** [comment] 2022-10-15 21:31
Please fill out the provided issue template for new device ports.

**Comment by z3ntu** [comment] 2022-11-20 11:37
Duplicate of #1947

**Closed as not planned by z3ntu** 2022-11-20 11:37 UTC
Labels: duplicate, Device Support
