### ISSUE TITLE
request for device 1532:027A

### ISSUE THREAD

**Issue by WantClue** [openrazer/razer-drivers#1979] opened 2022-12-09 21:19 UTC
### Support request for adding new device

- [ x] Have you tried rebooting?
- [ x] Have you looked at the [Troubleshooting](https://github.com/openrazer/openrazer/wiki/Troubleshooting) page?

Will we get support for the 1532:027A keyboard?

I use a razer blade 15 2022 base model and this keyboard seems to be not supported and is not recognised by openrazer.
Would love to see suppor for this aswell

**Comment by z3ntu** [comment] 2022-12-09 21:20
Duplicate of #1581

**Closed as completed by z3ntu** 2022-12-09 21:20 UTC
Labels: duplicate, support
