### ISSUE TITLE
Support for [Razer Blackshark V2 Pro]

### ISSUE THREAD

**Issue by MonadMania** [openrazer/razer-drivers#2258] opened 2024-06-02 06:00 UTC
### Device Info

* Name: Razer BlackShark V2 Pro
* Product Number: 1532:0528
* Model Number: IPIG-KOR-210726GY

### Device Information
```
Please post the output of
    lsusb -d 1532: -v
```
Bus 001 Device 004: ID 1532:0528 Razer USA, Ltd Razer BlackShark V2 Pro
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0 [unknown]
  bDeviceSubClass         0 [unknown]
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0528 Razer BlackShark V2 Pro
  bcdDevice            1.00
  iManufacturer           3 Razer
  iProduct                4 Razer BlackShark V2 Pro
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0114
    bNumInterfaces          4
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           0
      bInterfaceClass         1 Audio
      bInterfaceSubClass      1 Control Device
      bInterfaceProtocol      0 
      iInterface              1 Razer BlackShark V2 Pro
      AudioControl Interface Descriptor:
        bLength                10
        bDescriptorType        36
        bDescriptorSubtype      1 (HEADER)
        bcdADC               1.00
        wTotalLength       0x0047
        bInCollection           2
        baInterfaceNr(0)        1
        baInterfaceNr(1)        2
      AudioControl Interface Descriptor:
        bLength                12
        bDescriptorType        36
        bDescriptorSubtype      2 (INPUT_TERMINAL)
        bTerminalID             6
        wTerminalType      0x0201 Microphone
        bAssocTerminal          0
        bNrChannels             1
        wChannelConfig     0x0000
        iChannelNames           0 
        iTerminal               0 
      AudioControl Interface Descriptor:
        bLength                 9
        bDescriptorType        36
        bDescriptorSubtype      6 (FEATURE_UNIT)
        bUnitID                 3
        bSourceID               6
        bControlSize            1
        bmaControls(0)       0x02
          Volume Control
        bmaControls(1)       0x00
        iFeature                0 
      AudioControl Interface Descriptor:
        bLength                 9
        bDescriptorType        36
        bDescriptorSubtype      3 (OUTPUT_TERMINAL)
        bTerminalID             7
        wTerminalType      0x0101 USB Streaming
        bAssocTerminal          0
        bSourceID               3
        iTerminal               0 
      AudioControl Interface Descriptor:
        bLength                12
        bDescriptorType        36
        bDescriptorSubtype      2 (INPUT_TERMINAL)
        bTerminalID             1
        wTerminalType      0x0101 USB Streaming
        bAssocTerminal          0
        bNrChannels             2
        wChannelConfig     0x0003
          Left Front (L)
          Right Front (R)
        iChannelNames           0 
        iTerminal               0 
      AudioControl Interface Descriptor:
        bLength                10
        bDescriptorType        36
        bDescriptorSubtype      6 (FEATURE_UNIT)
        bUnitID                 2
        bSourceID               1
        bControlSize            1
        bmaControls(0)       0x01
          Mute Control
        bmaControls(1)       0x00
        bmaControls(2)       0x00
        iFeature                0 
      AudioControl Interface Descriptor:
        bLength                 9
        bDescriptorType        36
        bDescriptorSubtype      3 (OUTPUT_TERMINAL)
        bTerminalID             5
        wTerminalType      0x0301 Speaker
        bAssocTerminal          0
        bSourceID               2
        iTerminal               0 
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           0
      bInterfaceClass         1 Audio
      bInterfaceSubClass      2 Streaming
      bInterfaceProtocol      0 
      iInterface              0 
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       1
      bNumEndpoints           1
      bInterfaceClass         1 Audio
      bInterfaceSubClass      2 Streaming
      bInterfaceProtocol      0 
      iInterface              0 
      AudioStreaming Interface Descriptor:
        bLength                 7
        bDescriptorType        36
        bDescriptorSubtype      1 (AS_GENERAL)
        bTerminalLink           7
        bDelay                  0 frames
        wFormatTag         0x0001 PCM
      AudioStreaming Interface Descriptor:
        bLength                14
        bDescriptorType        36
        bDescriptorSubtype      2 (FORMAT_TYPE)
        bFormatType             1 (FORMAT_TYPE_I)
        bNrChannels             1
        bSubframeSize           2
        bBitResolution         16
        bSamFreqType            2 Discrete
        tSamFreq[ 0]        16000
        tSamFreq[ 1]        48000
      Endpoint Descriptor:
        bLength                 9
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes           13
          Transfer Type            Isochronous
          Synch Type               Synchronous
          Usage Type               Data
        wMaxPacketSize     0x0090  1x 144 bytes
        bInterval               1
        bRefresh                0
        bSynchAddress           0
        AudioStreaming Endpoint Descriptor:
          bLength                 7
          bDescriptorType        37
          bDescriptorSubtype      1 (EP_GENERAL)
          bmAttributes         0x01
            Sampling Frequency
          bLockDelayUnits         0 Undefined
          wLockDelay         0x0000
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           0
      bInterfaceClass         1 Audio
      bInterfaceSubClass      2 Streaming
      bInterfaceProtocol      0 
      iInterface              0 
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       1
      bNumEndpoints           1
      bInterfaceClass         1 Audio
      bInterfaceSubClass      2 Streaming
      bInterfaceProtocol      0 
      iInterface              0 
      AudioStreaming Interface Descriptor:
        bLength                 7
        bDescriptorType        36
        bDescriptorSubtype      1 (AS_GENERAL)
        bTerminalLink           1
        bDelay                  0 frames
        wFormatTag         0x0001 PCM
      AudioStreaming Interface Descriptor:
        bLength                14
        bDescriptorType        36
        bDescriptorSubtype      2 (FORMAT_TYPE)
        bFormatType             1 (FORMAT_TYPE_I)
        bNrChannels             1
        bSubframeSize           2
        bBitResolution         16
        bSamFreqType            2 Discrete
        tSamFreq[ 0]        16000
        tSamFreq[ 1]        48000
      Endpoint Descriptor:
        bLength                 9
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes           13
          Transfer Type            Isochronous
          Synch Type               Synchronous
          Usage Type               Data
        wMaxPacketSize     0x0090  1x 144 bytes
        bInterval               1
        bRefresh                0
        bSynchAddress           0
        AudioStreaming Endpoint Descriptor:
          bLength                 7
          bDescriptorType        37
          bDescriptorSubtype      1 (EP_GENERAL)
          bmAttributes         0x01
            Sampling Frequency
          bLockDelayUnits         0 Undefined
          wLockDelay         0x0000
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       2
      bNumEndpoints           1
      bInterfaceClass         1 Audio
      bInterfaceSubClass      2 Streaming
      bInterfaceProtocol      0 
      iInterface              0 
      AudioStreaming Interface Descriptor:
        bLength                 7
        bDescriptorType        36
        bDescriptorSubtype      1 (AS_GENERAL)
        bTerminalLink           1
        bDelay                  0 frames
        wFormatTag         0x0001 PCM
      AudioStreaming Interface Descriptor:
        bLength                20
        bDescriptorType        36
        bDescriptorSubtype      2 (FORMAT_TYPE)
        bFormatType             1 (FORMAT_TYPE_I)
        bNrChannels             2
        bSubframeSize           2
        bBitResolution         16
        bSamFreqType            4 Discrete
        tSamFreq[ 0]         8000
        tSamFreq[ 1]        22050
        tSamFreq[ 2]        44100
        tSamFreq[ 3]        48000
      Endpoint Descriptor:
        bLength                 9
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes           13
          Transfer Type            Isochronous
          Synch Type               Synchronous
          Usage Type               Data
        wMaxPacketSize     0x0120  1x 288 bytes
        bInterval               1
        bRefresh                0
        bSynchAddress           0
        AudioStreaming Endpoint Descriptor:
          bLength                 7
          bDescriptorType        37
          bDescriptorSubtype      1 (EP_GENERAL)
          bmAttributes         0x01
            Sampling Frequency
          bLockDelayUnits         0 Undefined
          wLockDelay         0x0000
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        3
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 [unknown]
      bInterfaceProtocol      0 
      iInterface              2 Hid Interface
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     426
          Report Descriptors: 
            ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0020  1x 32 bytes
        bInterval               1
Device Status:     0x0000
  (Bus Powered)

```
Please post the output of
    ls -lah /dev/input/by-id/
```
total 0
drwxr-xr-x. 2 root root 200 Jun  1 22:31 .
drwxr-xr-x. 4 root root 560 Jun  1 22:31 ..
lrwxrwxrwx. 1 root root   9 Jun  1 22:24 usb-ASRock_LED_Controller_A02019100900-event-joystick -> ../event2
lrwxrwxrwx. 1 root root   6 Jun  1 22:24 usb-ASRock_LED_Controller_A02019100900-joystick -> ../js0
lrwxrwxrwx. 1 root root   9 Jun  1 22:24 usb-Logitech_G203_LIGHTSYNC_Gaming_Mouse_2061386F5642-event-mouse -> ../event5
lrwxrwxrwx. 1 root root   9 Jun  1 22:24 usb-Logitech_G203_LIGHTSYNC_Gaming_Mouse_2061386F5642-if01-event-kbd -> ../event6
lrwxrwxrwx. 1 root root   9 Jun  1 22:24 usb-Logitech_G203_LIGHTSYNC_Gaming_Mouse_2061386F5642-mouse -> ../mouse0
lrwxrwxrwx. 1 root root   9 Jun  1 22:24 usb-Logitech_Gaming_Keyboard_G213_027B31403438-event-kbd -> ../event3
lrwxrwxrwx. 1 root root   9 Jun  1 22:24 usb-Logitech_Gaming_Keyboard_G213_027B31403438-if01-event-kbd -> ../event4
lrwxrwxrwx. 1 root root  10 Jun  1 22:31 usb-Razer_Razer_BlackShark_V2_Pro-event-if03 -> ../event21

<details>

```
Please post the output of
    usbhid-dump -m 1532 -ed
```
001:004:003:DESCRIPTOR         1717307872.662641
 05 0C 09 01 A1 01 85 01 09 E9 09 EA 09 E2 75 01
 95 03 15 00 25 01 81 02 75 05 95 01 81 03 95 03
 75 01 09 B6 09 CD 09 B5 81 02 75 15 95 01 81 03
 C0 06 C0 FF 09 01 A1 01 09 0A A1 02 85 64 09 0B
 75 04 25 0D 81 02 75 01 95 04 81 03 C0 09 14 A1
 02 85 65 09 15 09 16 09 17 95 03 25 01 81 02 75
 05 95 01 81 03 C0 C0 06 00 FF 09 01 A1 01 09 0A
 A1 02 85 FF 75 20 09 0B 17 01 00 00 80 27 FF FF
 FF 7F 81 02 C0 09 22 A1 02 85 90 09 33 75 08 15
 00 26 FF 00 81 02 09 34 81 02 05 01 09 3B 75 10
 27 FF FF 00 00 81 02 06 00 FF 09 0A A1 02 05 0A
 19 01 29 0A 95 0A 75 08 26 FF 00 81 02 C0 C0 06
 00 FF 09 22 A1 02 85 90 09 33 95 01 91 02 09 34
 91 02 05 01 09 3B 75 10 27 FF FF 00 00 91 02 06
 00 FF 09 0A A1 02 05 0A 19 01 29 0A 95 0A 75 08
 26 FF 00 91 02 C0 C0 06 00 FF 09 22 A1 02 85 C4
 09 33 95 01 81 02 09 34 81 02 05 01 09 3B 75 10
 27 FF FF 00 00 81 02 06 00 FF 09 0A A1 02 05 0A
 19 01 29 3B 95 3B 75 08 26 FF 00 81 02 C0 C0 06
 00 FF 09 22 A1 02 85 C4 09 33 95 01 91 02 09 34
 91 02 05 01 09 3B 75 10 27 FF FF 00 00 91 02 06
 00 FF 09 0A A1 02 05 0A 19 01 29 3B 95 3B 75 08
 26 FF 00 91 02 C0 C0 06 00 FF 09 0C A1 02 85 FF
 05 01 09 3B 95 01 B1 02 09 3A A1 02 05 0A 19 01
 29 3E 95 3E B1 02 C0 C0 06 00 FF 09 0C A1 02 85
 E2 05 01 09 3B 95 01 81 02 09 3A A1 02 05 0A 19
 01 29 3E 95 3E 81 02 C0 C0 C0

</details>

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<Screenshots of all available options as seen on **Razer Synapse** in a Windows Environment>

**Comment by makarov-roman** [comment] 2024-06-03 09:26
there is https://github.com/openrazer/openrazer/issues/1280
but 2020 and 2023 versions are technically difference headsets, so I'm not sure if it makes sense to have a single issue for both of them

**Comment by z3ntu** [comment] 2024-06-05 19:13
Duplicate of #1280

**Closed as not planned by z3ntu** 2024-06-05 19:13 UTC
Labels: duplicate, Device Support
