### ISSUE TITLE
Device 1532:0096 not supported

### ISSUE THREAD

**Issue by iamagarre** [openrazer/razer-drivers#1903] opened 2022-08-30 22:24 UTC
Hi,

this is my first support ticket so I hope to do it right.

I currently have a razer keyboard and a razer mouse. Mouse is a Razer Naga X, the keyboard is a Razer Blackwidow v3. The keyboard works fine with openrazer and polychromatic but the mouse shows a message that is not supported. I have readed in another support issue that support for Razer Naga X was already added but mine is not working.

Any idea why keyboard works and mouse does not?

Best Regards

**Comment by Etaash-mathamsetty** [comment] 2022-08-31 00:48
you have to compile openrazer from this PR https://github.com/openrazer/openrazer/pull/1878, while we wait for it to get merged and become part of the next release
also this is a duplicate of #1463

**Comment by iamagarre** [comment] 2022-08-31 07:57
Thank you and sorry for the duplicate.

**Comment by z3ntu** [comment] 2022-10-15 17:03
Closing then.

**Closed as not planned by z3ntu** 2022-10-15 17:03 UTC
Labels: support
