### ISSUE TITLE
Razer Blade 15 Base (mid 2021) Keyboard Color

### ISSUE THREAD

**Issue by gr558** [openrazer/razer-drivers#1783] opened 2022-04-01 04:59 UTC
```
Hello,

My Blade 15 is awesome...but I can't change the keyboard color. 
I'm grateful that you've created this project, and was wondering if you might be willing 
to add my model-type to your device list?

(Polychromatic seems to pass everything but the Device Check.) 

Most of the output that you have asked for is included below.

I'm somewhat of a newbie so the reverse engineering environment needed for USB packets might be a bit 
over my head. For now...setting up a '.pcapng' testing environment will be a significant learning curve -- 
so please let me know if these results are essential to solve this issue. 

The Blade in question has a single-zone RGB keyboard.

I appreciate all of your capabilities and efforts that enable Razer equipment to work better with Linux. 


Sincerely,
GR558
```

### Device Info

* Name: **Razer Blade 15 Base (mid 2021)**
* Product Number: **RZ09-0410BEA2-R3U1**
* Model Number: **1532:027A**

### Device Information
```
Please post the output of
    lsusb -d 1532: -v
```
[lsusb_output.txt](https://github.com/openrazer/openrazer/files/8394392/lsusb_output.txt)

```
Please post the output of
    ls -lah /dev/input/by-id/
```
[ls-iah_output.txt](https://github.com/openrazer/openrazer/files/8394395/ls-iah_output.txt)

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
```
Other Details: 
When the laptop was delivered, I swapped the factory hard drive for an empty one and installed Linux 
(Arch - very minimal with the exception of KDE.)

Here is the output from Polychromatic
```
![Polychromatic_Output](https://user-images.githubusercontent.com/102775327/161188235-331e7cc2-dbd3-426c-b99f-d495bd3679b0.jpg)

**Comment by z3ntu** [comment] 2022-04-07 18:52
Duplicate of #1581

**Closed as completed by z3ntu** 2022-04-07 18:52 UTC
Labels: duplicate, Device Support
