### ISSUE TITLE
Support for Basilisk X Hyperspeed V3

### ISSUE THREAD

**Issue by Lorkrei** [openrazer/razer-drivers#2112] opened 2023-08-12 13:46 UTC
### Device Info

* Name: Basilisk X Hyperspeed V3
* Product Number: RZ01-04870100-R3G1
* Model Number: RC30-04870100-000

### Device Information
```
Please post the output of
    lsusb -d 1532: -v
```

```
Please post the output of
    ls -lah /dev/input/by-id/
```

<details>

```
Please post the output of
    usbhid-dump -m 1532 -ed
```

</details>

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
<Screenshots of all available options as seen on **Razer Synapse** in a Windows Environment>

**Comment by Lorkrei** [comment] 2023-08-12 13:48
sorry these are all the information i can get for this device

**Comment by z3ntu** [comment] 2023-08-13 09:22
Appears to be a duplicate of #2069 , not 100% sure because you didn't provide e.g. `lsusb | grep 1532` output.

**Closed as not planned by z3ntu** 2023-08-13 09:22 UTC
Labels: duplicate, Device Support

**Comment by Lorkrei** [comment] 2023-08-13 09:41
Hello.
I don't know how provide the data you need.
Can you tell me how?

Thanks

Il Dom 13 Ago 2023, 11:22 Luca Weiss ***@***.***> ha scritto:

**Comment by z3ntu** [comment] 2023-08-13 09:50
Run the command `lsusb | grep 1532` in your terminal and copy paste the output here. But as I said probably it's a duplicate.
