### ISSUE TITLE
Device 1532:026B not recognized

### ISSUE THREAD

**Issue by ciwin** [openrazer/razer-drivers#1792] opened 2022-04-09 15:10 UTC
Hi,
I have a new Razer Huntsman V2 Tenkeyless under Ubuntu 20.04.2 Linux, but the device ID 1532:026B  is not recognized and supported by OpenRazor. Is there an easy way to fix this or Is somebody working on a driver update? 
Thanks!
Christoph

**Comment by z3ntu** [comment] 2022-04-09 15:11
Duplicate of #1681

**Closed as completed by z3ntu** 2022-04-09 15:11 UTC
Labels: duplicate, support
