### ISSUE TITLE
Support for Razer Naga V2 Pro

### ISSUE THREAD

**Issue by stlhrt** [openrazer/razer-drivers#1991] opened 2022-12-28 00:15 UTC
### Device Info

* Name: Razer Naga V2 Pro
* Product Number: RZ01-04400100-R3G1
* Model Number: RZ01-0440

### Device Information
```

Bus 001 Device 014: ID 1532:00a8 Razer USA, Ltd Razer Naga V2 Pro
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x00a8 
  bcdDevice            1.00
  iManufacturer           1 Razer
  iProduct                2 Razer Naga V2 Pro
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     100
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     314
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
Device Status:     0x0000
  (Bus Powered)
```

```
lrwxrwxrwx 1 root root  10 Dec 28 00:22 usb-Razer_Razer_Naga_V2_Pro-event-if01 -> ../event12
lrwxrwxrwx 1 root root  10 Dec 28 00:22 usb-Razer_Razer_Naga_V2_Pro-event-mouse -> ../event13
lrwxrwxrwx 1 root root  10 Dec 28 00:22 usb-Razer_Razer_Naga_V2_Pro-if01-event-kbd -> ../event10
lrwxrwxrwx 1 root root  10 Dec 28 00:22 usb-Razer_Razer_Naga_V2_Pro-if01-event-mouse -> ../event11
lrwxrwxrwx 1 root root   9 Dec 28 00:22 usb-Razer_Razer_Naga_V2_Pro-if01-mouse -> ../mouse1
lrwxrwxrwx 1 root root   9 Dec 28 00:22 usb-Razer_Razer_Naga_V2_Pro-if02-event-kbd -> ../event9
lrwxrwxrwx 1 root root   9 Dec 28 00:22 usb-Razer_Razer_Naga_V2_Pro-mouse -> ../mouse2

```

<details>

```
001:014:002:DESCRIPTOR         1672185504.102893
 05 01 09 06 A1 01 05 07 19 E0 29 E7 15 00 25 01
 75 01 95 08 81 02 81 01 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 06 81 00 05 08 19 01 29 03 15 00
 25 01 75 01 95 03 91 02 95 05 91 01 C0

001:014:001:DESCRIPTOR         1672185504.104055
 05 01 09 06 A1 01 85 01 05 07 19 E0 29 E7 15 00
 25 01 75 01 95 08 81 02 19 00 2A FF 00 15 00 26
 FF 00 75 08 95 0E 81 00 05 08 19 01 29 03 15 00
 25 01 75 01 95 03 91 02 95 05 91 01 C0 05 01 09
 02 A1 01 85 0A 09 01 A1 00 05 09 19 01 29 06 15
 00 25 01 75 01 95 06 81 02 75 01 95 02 81 03 06
 00 FF 09 40 75 08 95 02 15 81 25 7F 81 02 05 01
 09 38 15 81 25 7F 75 08 95 01 81 06 09 30 09 31
 16 00 80 26 FF 7F 75 10 95 02 81 06 C0 C0 05 0C
 09 01 A1 01 85 02 19 00 2A 3C 02 15 00 26 3C 02
 95 01 75 10 81 00 75 08 95 0D 81 01 C0 05 01 09
 80 A1 01 85 03 19 81 29 83 15 00 25 01 75 01 95
 03 81 02 95 05 81 01 75 08 95 0E 81 01 C0 05 01
 09 00 A1 01 85 04 09 03 15 00 26 FF 00 35 00 46
 FF 00 75 08 95 0F 81 00 C0 05 01 09 00 A1 01 85
 05 09 03 15 00 26 FF 00 35 00 46 FF 00 75 08 95
 0F 81 00 C0 05 01 09 00 A1 01 85 08 09 03 15 00
 26 FF 00 35 00 46 FF 00 75 08 95 0F 81 00 C0 05
 01 09 00 A1 01 85 09 09 03 15 00 26 FF 00 35 00
 46 FF 00 75 08 95 0F 81 00 C0

001:014:000:DESCRIPTOR         1672185504.105948
 05 01 09 02 A1 01 09 01 A1 00 05 09 19 01 29 05
 15 00 25 01 75 01 95 05 81 02 75 01 95 03 81 03
 75 01 95 08 81 03 05 0C 0A 38 02 15 81 25 7F 75
 08 95 01 81 06 05 01 09 38 15 81 25 7F 75 08 95
 01 81 06 09 30 09 31 16 00 80 26 FF 7F 75 10 95
 02 81 06 C0 06 00 FF 09 02 15 00 25 01 75 08 95
 5A B1 01 C0

```

</details>

### Packet Captures

<Please see here as we probably need packet captures>
<https://github.com/openrazer/openrazer/wiki/Reverse-Engineering-USB-Protocol>

### Synapse Screenshots
![naga_v2_pro_1](https://user-images.githubusercontent.com/3652939/209738647-dc7956bf-f730-4fc7-98ba-679ee9d6a593.png)

![naga_v2_pro_2](https://user-images.githubusercontent.com/3652939/209738653-eefa2644-6989-44f4-8753-f42f434e5afb.png)

![naga_v2_pro_3](https://user-images.githubusercontent.com/3652939/209738664-476a5ebf-a7f5-4f18-b069-65a0f20973bd.png)

![naga_v2_pro_4](https://user-images.githubusercontent.com/3652939/209738673-f7f3692a-0bbe-4359-91bd-6d1ab24be243.png)

![naga_v2_pro_5](https://user-images.githubusercontent.com/3652939/209738682-de212eee-945b-4ccb-92fe-c9f377bd9d4f.png)

![naga_v2_pro_6](https://user-images.githubusercontent.com/3652939/209738687-b10d92e0-df02-4de3-a2ea-106c86c778ea.png)

![naga_v2_pro_7](https://user-images.githubusercontent.com/3652939/209738695-24b44173-cc1c-4d93-87d5-982ec83e515c.png)

![naga_v2_pro_8](https://user-images.githubusercontent.com/3652939/209738701-35b12c94-646f-47ff-b4f2-4b9ad90b9d43.png)

![naga_v2_pro_9](https://user-images.githubusercontent.com/3652939/209738707-cab9c62b-fae6-4e30-9964-e5ed9830325f.png)

**Comment by z3ntu** [comment] 2023-01-09 17:53
Duplicate of #1952

**Closed as not planned by z3ntu** 2023-01-09 17:53 UTC
Labels: duplicate, Device Support
