### ISSUE TITLE
Razer Huntsman v2 Tenkeyless - Not recognized 

### ISSUE THREAD

**Issue by jrwagh333** [openrazer/razer-drivers#1750] opened 2022-02-12 14:20 UTC
Model Name: Razer Huntsman v2 Tenkelyless (TKL) (Tournamnet Edition)
Model Number: RZ03-03941600-R3W1

**Comment by z3ntu** [comment] 2022-02-19 19:44
Duplicate of #1681

**Closed as completed by z3ntu** 2022-02-19 19:44 UTC
Labels: duplicate
