### ISSUE TITLE
Support for Razer BlackWidow V3 Pro [1532:025A]

### ISSUE THREAD

**Issue by wasertech** [openrazer/razer-drivers#1625] opened 2021-10-02 21:49 UTC
### Device Info

* Name: Razer BlackWidow V3 Pro
* Product Number: 1532:025A
* Model Number: RZ03-0353

### Device Information
```
Bus 003 Device 010: ID 1532:025a Razer USA, Ltd Razer BlackWidow V3 Pro
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x025a 
  bcdDevice            2.00
  iManufacturer           1 Razer
  iProduct                2 Razer BlackWidow V3 Pro
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x006d
    bNumInterfaces          4
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     177
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      90
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        3
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     348
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x84  EP 4 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1

Bus 001 Device 002: ID 1532:022b Razer USA, Ltd Tartarus V2
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x022b Tartarus V2
  bcdDevice            2.00
  iManufacturer           1 Razer
  iProduct                2 Razer Tartarus V2
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0054
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
Device Status:     0x0000
  (Bus Powered)
```

```
drwxr-xr-x root root 360 B Sat Oct  2 23:19:27 2021  .
drwxr-xr-x root root 760 B Sat Oct  2 23:19:27 2021  ..
lrwxrwxrwx root root  10 B Sat Oct  2 22:56:55 2021  usb-046d_G27_Racing_Wheel-event-joystick ⇒ ../event27
lrwxrwxrwx root root   6 B Sat Oct  2 22:56:55 2021  usb-046d_G27_Racing_Wheel-joystick ⇒ ../js1
lrwxrwxrwx root root  10 B Sat Oct  2 22:56:55 2021  usb-Madcatz_Mad_Catz_R.A.T.3_Mouse-event-mouse ⇒ ../event20
lrwxrwxrwx root root   9 B Sat Oct  2 22:56:55 2021  usb-Madcatz_Mad_Catz_R.A.T.3_Mouse-mouse ⇒ ../mouse1
lrwxrwxrwx root root  10 B Sat Oct  2 23:19:27 2021  usb-Razer_Razer_BlackWidow_V3_Pro-event-if01 ⇒ ../event23
lrwxrwxrwx root root  10 B Sat Oct  2 23:19:27 2021  usb-Razer_Razer_BlackWidow_V3_Pro-event-if03 ⇒ ../event25
lrwxrwxrwx root root  10 B Sat Oct  2 23:19:27 2021  usb-Razer_Razer_BlackWidow_V3_Pro-event-kbd ⇒ ../event21
lrwxrwxrwx root root  10 B Sat Oct  2 23:19:27 2021  usb-Razer_Razer_BlackWidow_V3_Pro-if01-event-kbd ⇒ ../event22
lrwxrwxrwx root root  10 B Sat Oct  2 23:19:27 2021  usb-Razer_Razer_BlackWidow_V3_Pro-if02-event-mouse ⇒ ../event24
lrwxrwxrwx root root   9 B Sat Oct  2 23:19:27 2021  usb-Razer_Razer_BlackWidow_V3_Pro-if02-mouse ⇒ ../mouse2
lrwxrwxrwx root root  10 B Sat Oct  2 22:56:55 2021  usb-Razer_Razer_Tartarus_V2-event-kbd ⇒ ../event17
lrwxrwxrwx root root  10 B Sat Oct  2 22:56:55 2021  usb-Razer_Razer_Tartarus_V2-if01-event-kbd ⇒ ../event18
lrwxrwxrwx root root  10 B Sat Oct  2 22:56:55 2021  usb-Razer_Razer_Tartarus_V2-if02-event-mouse ⇒ ../event19
lrwxrwxrwx root root   9 B Sat Oct  2 22:56:55 2021  usb-Razer_Razer_Tartarus_V2-if02-mouse ⇒ ../mouse0
lrwxrwxrwx root root  10 B Sat Oct  2 22:56:56 2021  usb-Saitek_Saitek_X52_Flight_Control_System-event-joystick ⇒ ../event26
lrwxrwxrwx root root   6 B Sat Oct  2 22:56:56 2021  usb-Saitek_Saitek_X52_Flight_Control_System-joystick ⇒ ../js0

```

### Packet Captures

Really?

### Synapse Screenshots
As of my knowledge synaspe is not avalible on Linux. [Here is a screenshot of Polychroma instead](https://imgur.com/a/el1KZsw).

**Comment by lah7** [comment] 2021-10-02 22:14
Duplicate of #1619. It's the same as #1279 but the USB PID changes depending if it's wired/wireless.

There is a pull request implementing this device - please test #1622.

**Closed as completed by lah7** 2021-10-02 22:14 UTC
Labels: Device Support
