### ISSUE TITLE
Support for Razer Barracuda

### ISSUE THREAD

**Issue by PetrChundela954** [openrazer/razer-drivers#2356] opened 2024-12-09 19:57 UTC
### Device Name

Razer Barracuda

### Product Number

.

### Model Number

.

### VID:PID

.

### USB Details

```shell
.
```

### Device Input Paths

```shell
.
```

**Comment by z3ntu** [comment] 2024-12-09 20:26
Duplicate of #2314

**Closed as not planned by z3ntu** 2024-12-09 20:26 UTC
Labels: duplicate, Device Support
