### ISSUE TITLE
Support for Ornata V3 Linux Ubuntu 22.04

### ISSUE THREAD

**Issue by xandervill** [openrazer/razer-drivers#2104] opened 2023-08-02 07:40 UTC
### Device Info

* Name: Ornata V3
* Product Number: RZ03-04460800-R3R1
* Model Number: RZ03-0446

Hello.
In applications Polychromatic and RazerGenie Ornata V3 it is not defined. Will there be keyboard Ornata V3 support for Linux Ubuntu 22.04? If not, is it possible to use drivers from Ornata V2 and how to do it?

**Comment by xandervill** [comment] 2023-08-02 07:40
![image](https://github.com/openrazer/openrazer/assets/134795029/46918398-42b4-42b5-88ed-8a798accd84e)

**Comment by z3ntu** [comment] 2023-08-06 10:23
Duplicate of #2053

**Closed as not planned by z3ntu** 2023-08-06 10:23 UTC
Labels: duplicate, Device Support
